export const FILM_LIST_REQUEST = "FILM_LIST_REQUEST"
export const FILM_LIST_SUCCESS = "FILM_LIST_SUCCESS"
export const FILM_LIST_FAIL = "FILM_LIST_FAIL"

export const FILM_DETAIL_REQUEST = "FILM_DETAIL_REQUEST"
export const FILM_DETAIL_SUCCESS = "FILM_DETAIL_SUCCESS"
export const FILM_DETAIL_FAIL = "FILM_DETAIL_FAIL"

export const FILM_REVIEWS_REQUEST = "FILM_REVIEW_REQUEST"
export const FILM_REVIEWS_SUCCESS = "FILM_REVIEW_SUCCESS"
export const FILM_REVIEWS_FAIL = "FILM_REVIEWS_FAIL"
